// Generated by CoffeeScript 1.10.0
(function () {
    var Slack, autoMark, autoReconnect, slack, slackToken, regex, prot, host, jira_url;


    prot = process.env.JIRA_PROTOCOL || "http";
    host = process.env.JIRA_HOST || (console.error("Jira host not configured, process terminating") && process.exit(1));
    slackToken = process.env.SLACK_TOKEN || (console.error("Jira host not configured, process terminating") && process.exit(1));

    jira_url = prot + "://" + host + "/browse/";

    Slack = require('slack-client');

    autoReconnect = true;
    regex = /([A-Z]{1}[A-Z0-9]+\-[0-9]+)/g;

    autoMark = true;

    slack = new Slack(slackToken, autoReconnect, autoMark);

    slack.on('open', function () {
        return console.log("Connected to " + slack.team.name + " as @" + slack.self.name);
    });

    slack.on('message', function (message) {
        var text = message.text;
        const found = text.match(regex);
        if (found && found.length) {
            message.text = "Found JIRA tickets in message";
            var tickets = new Set();
            found.forEach(function (ticket) {
                if (!tickets.has(ticket)) {
                    tickets.add(ticket);
                    console.log(ticket);
                    message.text = jira_url + ticket;
                    slack._send(message);
                }
            });

        }
    });

    slack.on('error', function (err) {
        return console.error("Error", err);
    });

    slack.login();

}).call(this);
